### PR TITLE
Contact API deprecation solved and People API implementation added

### PR DESCRIPTION
**Pull request by moshfiqrony**

### CODE REVIEW

**Comment by moshfiqrony** [comment]
Is there anyone seeing this?

**Comment by kwent** [comment]
Thank you ! Released in 2.0.0 https://github.com/kwent/react-google-contacts/commit/0774f2b6fcf3ad666be07398b6a3da46f4c06b21

**Comment by moshfiqrony** [comment]
Why it shows old version here?
image

**Comment by kwent** [comment]
Added release in github as well. Enjoy

**Comment by moshfiqrony** [comment]
Thanks @kwent

**Pull request merged**
